//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ILuaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChunk([NotNull] LuaParser.ChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChunk([NotNull] LuaParser.ChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] LuaParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] LuaParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_empty([NotNull] LuaParser.Stat_emptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_empty([NotNull] LuaParser.Stat_emptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_globalassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_globalassign([NotNull] LuaParser.Stat_globalassignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_globalassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_globalassign([NotNull] LuaParser.Stat_globalassignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_functioncall([NotNull] LuaParser.Stat_functioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_functioncall([NotNull] LuaParser.Stat_functioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_label([NotNull] LuaParser.Stat_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_label([NotNull] LuaParser.Stat_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_break([NotNull] LuaParser.Stat_breakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_break([NotNull] LuaParser.Stat_breakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_goto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_goto([NotNull] LuaParser.Stat_gotoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_goto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_goto([NotNull] LuaParser.Stat_gotoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_do"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_do([NotNull] LuaParser.Stat_doContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_do"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_do([NotNull] LuaParser.Stat_doContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_while([NotNull] LuaParser.Stat_whileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_while([NotNull] LuaParser.Stat_whileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_repeat([NotNull] LuaParser.Stat_repeatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_repeat([NotNull] LuaParser.Stat_repeatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_if([NotNull] LuaParser.Stat_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_if([NotNull] LuaParser.Stat_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_fornum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_fornum([NotNull] LuaParser.Stat_fornumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_fornum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_fornum([NotNull] LuaParser.Stat_fornumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_foriter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_foriter([NotNull] LuaParser.Stat_foriterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_foriter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_foriter([NotNull] LuaParser.Stat_foriterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_functiondef([NotNull] LuaParser.Stat_functiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_functiondef([NotNull] LuaParser.Stat_functiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_localfunctiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_localfunctiondef([NotNull] LuaParser.Stat_localfunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_localfunctiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_localfunctiondef([NotNull] LuaParser.Stat_localfunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat_localassignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_localassignment([NotNull] LuaParser.Stat_localassignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat_localassignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_localassignment([NotNull] LuaParser.Stat_localassignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] LuaParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] LuaParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] LuaParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] LuaParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] LuaParser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] LuaParser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] LuaParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] LuaParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] LuaParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] LuaParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_nil"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_nil([NotNull] LuaParser.Exp_nilContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_nil"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_nil([NotNull] LuaParser.Exp_nilContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_bool([NotNull] LuaParser.Exp_boolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_bool([NotNull] LuaParser.Exp_boolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_number([NotNull] LuaParser.Exp_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_number([NotNull] LuaParser.Exp_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_string([NotNull] LuaParser.Exp_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_string([NotNull] LuaParser.Exp_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_params([NotNull] LuaParser.Exp_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_params([NotNull] LuaParser.Exp_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_functiondef([NotNull] LuaParser.Exp_functiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_functiondef([NotNull] LuaParser.Exp_functiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_prefixexp([NotNull] LuaParser.Exp_prefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_prefixexp([NotNull] LuaParser.Exp_prefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_tableconstructor([NotNull] LuaParser.Exp_tableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_tableconstructor([NotNull] LuaParser.Exp_tableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_unary([NotNull] LuaParser.Exp_unaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_unary([NotNull] LuaParser.Exp_unaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryop([NotNull] LuaParser.BinaryopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryop([NotNull] LuaParser.BinaryopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] LuaParser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] LuaParser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrExp([NotNull] LuaParser.VarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrExp([NotNull] LuaParser.VarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] LuaParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] LuaParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSuffix([NotNull] LuaParser.VarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSuffix([NotNull] LuaParser.VarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAndArgs([NotNull] LuaParser.NameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAndArgs([NotNull] LuaParser.NameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncbody([NotNull] LuaParser.FuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncbody([NotNull] LuaParser.FuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldlist([NotNull] LuaParser.FieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldlist([NotNull] LuaParser.FieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] LuaParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] LuaParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] LuaParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] LuaParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPower([NotNull] LuaParser.OperatorPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPower([NotNull] LuaParser.OperatorPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] LuaParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] LuaParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] LuaParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] LuaParser.StringContext context);
}
